filters:
  most_rate: "Most Rate"
  most_favorites: "Most Favorites"
activities:
  max_retrived_feed: 5
option_time:
  vn: "%a, %d %b %Y %H:%M:%S"
books:
  page: 20
timezone:
  vn: "Hanoi"
limit_activity: 8
mailing:
  from: "thetoan95@gmail.com"
  mail_host: "smtp.gmail.com"
  mail_port: "465"
  mail_domain: "gmail.com"
  host: "localhost:3000"
item_per_page: 15
excel:
  name: "Name"
  bio: "Bio"
  books: "Books"
  total: "Total"
  email: "Email"
  confirmed: "Confirmed?"
  role: "Role"
